### ISSUE TITLE
render errors spamming the log

### ISSUE THREAD

**Issue by Hypsellis** [team-abnormals/abnormals-core#75] opened 2021-02-05 04:52 UTC
These render errors keep spamming the game log.

```
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_stairs_inner_top
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain extrudes->extrudes in abnormals_core:block/thatch/thatch_stairs_inner_top
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_vertical_slab
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain extrudes->extrudes in abnormals_core:block/thatch/thatch_vertical_slab
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_stairs_inner
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain extrudes->extrudes in abnormals_core:block/thatch/thatch_stairs_inner
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_stairs_outer
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain extrudes->extrudes in abnormals_core:block/thatch/thatch_stairs_outer
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain thatch->thatch in abnormals_core:block/thatch/thatch_stairs_outer_top
[03:45:54] [Render thread/WARN]: Unable to resolve texture due to reference chain extrudes->extrudes in abnormals_core:block/thatch/thatch_stairs_outer_top
```

**Comment by bageldotjpg** [comment] 2021-02-05 05:11
Duplicate of #69, but it seems to be another mod causing it and can't do anything with a replication method

**Closed by bageldotjpg** 2021-02-05 05:11 UTC

**Comment by Hypsellis** [comment] 2021-02-05 05:29
Ah sorry for the duplicate.
