### ISSUE TITLE
log warnings for various Abnormals mods

### ISSUE THREAD

**Issue by violetazx** [team-abnormals/abnormals-core#128] opened 2021-09-30 23:04 UTC
Minecraft: 1.16.5
Forge: 36.2.0
Modloader: Curseforge

Mod list:
 - Abnormals Core (3.3.0)
 - Atmospheric (3.1.0)
 - Autumnity (2.1.1)
 - Berry Good (4.1.1)
 - Buzzier Bees (3.0.1)
 - Endergetic (3.0.0)
 - Environmental (1.1.0)
 - Savage and Ravage (3.1.0)
 - Upgrade: Aquatic (3.1.0)

Issue:
I noticed a bunch of warnings in my [latest.log](https://pastebin.com/3SM3VWYv) and just wanted to know if they indicated any issues? I tried spawning a few of the mobs in creative that it was giving warnings for, and they spawn fine, so there doesn't seem to be any issue, but I want to make sure. They're all the same:
[Render thread/WARN]: Called deprecated GlobalEntityTypeAttributes#put for **xyz**, use EntityAttributeCreationEvent instead.

Am also concerned about this error:
[Render thread/ERROR]: Error adding element: Base value out of range: 256 [-10-128]
Don't know what it is, want to be sure it's nothing bad.

**Comment by SmellyModder** [comment] 2021-10-02 13:21
Abnormals Core is not a place to open issues about all Abnormals Mods.

The mods giving the `Called deprecated GlobalEntityTypeAttributes#put for xyz, use EntityAttributeCreationEvent instead.` warning have that warning fixed in development.

`[Render thread/ERROR]: Error adding element: Base value out of range: 256 [-10-128]`:
This is an error caused by Endergetic that has been fixed in development. The error shouldn't cause any big issues.

**Closed by SmellyModder** 2021-10-02 13:21 UTC
